### ISSUE TITLE
ros_melodic?

### ISSUE THREAD

**Issue by yeqianchen** [robot-learning-freiburg/ros_sam#5]
I am currently reproducing your algorithm on Ubuntu 18.04 with ROS Melodic. However, I encountered some issues. I've created a virtual environment named 'ros_sam' using Anaconda and installed necessary libraries. During compilation, I used the command 'catkin_make -DPYTHON_EXECUTABLE=/home/aba/anaconda3/envs/ros_sam/bin/python' to specify the required Python version. But I keep encountering similar errors.
![Screenshot from 2023-12-20 15-37-14](https://github.com/robot-learning-freiburg/ros_sam/assets/103102536/36a3bb4c-eca4-4929-b735-4cc1a4e839be)

**Comment by ARoefer** [comment]
Hello! I'm afraid I cannot help you with this issue, as I have not used melodic in a long time and also do not use anaconda. We do not officially support melodic because it is stuck on Python 2 and officially also discontinued. From the stack trace, it seems like it has something to do with the message generation step. Maybe you can google in that direction.
